apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jojb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-jojb@sha256:27af8e07bd406c7408cb6ddf3f3fe3d33dabad82821cad1d8ef2c3f5a99f821d
        name: my-nodejs
        resources: {}
status: {}
